package org.tamalin.panthersleek.resources.plaf; /**
 * File skeleton generated by IntelliJ IDEA.
 * @author Quytelda K. Gaiwin
 * Date: Dec 8, 2010
 * Time: 12:33:55 PM
 */

/**
 * @author Quytelda K. Gaiwin
 */

public interface EventHandler
{
    public boolean eventTriggered();
}
